# Generated by Zibuu MCP
spawn-protection=16
max-tick-time=60000
gamemode=survival
force-gamemode=false
difficulty=easy
max-players=20
network-compression-threshold=256
max-world-size=29999984
server-port={{PORT}}
allow-nether=true
enable-command-block=false
spawn-animals=true
spawn-npcs=true
enable-rcon=false
